<template>
  <label ref="root" class="section-input"><span class="section-input__label">Раздел</span><span class="section-input__control" :class="{open:isOpen}"><input :value="modelValue" type="text" placeholder="Учёба, Работа, Проекты…" role="combobox" aria-autocomplete="list" :aria-expanded="isOpen" @focus="open" @input="handleInput" @keydown="handleKeydown"><button type="button" aria-label="Показать разделы" @click.prevent="toggle"><UiIcon name="down"/></button></span>
    <Transition name="section-options"><span v-if="isOpen" class="section-input__panel" role="listbox"><button v-for="(option,index) in filteredOptions" :key="option" type="button" role="option" :aria-selected="normalize(option)===normalize(modelValue)" :class="{active:highlightedIndex===index}" @mousedown.prevent="select(option)" @mouseenter="highlightedIndex=index"><span class="section-input__icon"><UiIcon name="folder"/></span><span><strong>{{ option }}</strong><small>Раздел базы знаний</small></span><UiIcon v-if="normalize(option)===normalize(modelValue)" name="check"/></button><button v-if="canCreate" type="button" class="section-input__create" :class="{active:highlightedIndex===filteredOptions.length}" @mousedown.prevent="acceptNew" @mouseenter="highlightedIndex=filteredOptions.length"><span class="section-input__icon">+</span><span><strong>Создать «{{ modelValue.trim() }}»</strong><small>Появится в навигации и графе</small></span></button><p v-if="!filteredOptions.length&&!canCreate">Начни вводить название нового раздела</p></span></Transition>
  </label>
</template>
<script setup>
import {computed,onBeforeUnmount,onMounted,ref} from 'vue';import UiIcon from '../../../components/ui/UiIcon.vue'
const props=defineProps({modelValue:{type:String,default:''},options:{type:Array,default:()=>[]}});const emit=defineEmits(['update:modelValue']);const root=ref(null);const isOpen=ref(false);const highlightedIndex=ref(-1)
const normalizedOptions=computed(()=>Array.from(new Map(props.options.filter(Boolean).map(option=>[normalize(option),String(option).trim()])).values()));const filteredOptions=computed(()=>{const query=normalize(props.modelValue);return normalizedOptions.value.filter(option=>!query||normalize(option).includes(query)).slice(0,8)});const canCreate=computed(()=>Boolean(props.modelValue.trim())&&!normalizedOptions.value.some(option=>normalize(option)===normalize(props.modelValue)));const itemCount=computed(()=>filteredOptions.value.length+Number(canCreate.value))
function normalize(value){return String(value||'').trim().toLocaleLowerCase('ru-RU').replace(/ё/g,'е')}function open(){isOpen.value=true;highlightedIndex.value=-1}function close(){isOpen.value=false;highlightedIndex.value=-1}function toggle(){isOpen.value?close():open()}function handleInput(event){emit('update:modelValue',event.target.value);open()}function select(value){emit('update:modelValue',value);close()}function acceptNew(){emit('update:modelValue',props.modelValue.trim());close()}function handleKeydown(event){if(['ArrowDown','ArrowUp'].includes(event.key)){event.preventDefault();if(!isOpen.value)return open();if(!itemCount.value)return;const direction=event.key==='ArrowDown'?1:-1;highlightedIndex.value=(highlightedIndex.value+direction+itemCount.value)%itemCount.value}else if(event.key==='Enter'&&isOpen.value&&highlightedIndex.value>=0){event.preventDefault();const option=filteredOptions.value[highlightedIndex.value];option?select(option):acceptNew()}else if(event.key==='Escape')close()}function handleOutside(event){if(!root.value?.contains(event.target))close()}onMounted(()=>document.addEventListener('pointerdown',handleOutside));onBeforeUnmount(()=>document.removeEventListener('pointerdown',handleOutside))
</script>
<style scoped>
.section-input{position:relative;min-width:0;display:grid;gap:5px}.section-input__label{color:var(--text-secondary);font-size:11px;font-weight:700}.section-input__control{display:grid;grid-template-columns:minmax(0,1fr) 36px;align-items:center;border:1px solid var(--border-color);border-radius:var(--radius-md);background:var(--field-bg);transition:.18s var(--ease-out)}.section-input__control:focus-within,.section-input__control.open{border-color:var(--accent-border);background:var(--field-bg-focus);box-shadow:0 0 0 3px var(--accent-soft)}.section-input__control input{width:100%;min-width:0;min-height:38px;border:0;padding:0 11px;color:var(--text-primary);background:transparent;outline:0}.section-input__control>button{height:28px;display:grid;place-items:center;border:0;border-left:1px solid var(--border-color);color:var(--text-muted);background:transparent}.section-input__control.open>button{transform:rotate(180deg)}.section-input__panel{position:absolute;z-index:30;top:calc(100% + 6px);right:0;left:0;display:grid;gap:3px;max-height:300px;overflow-y:auto;border:1px solid var(--border-strong);border-radius:13px;padding:5px;background:color-mix(in srgb,var(--card-solid) 97%,transparent);box-shadow:0 20px 48px rgb(0 0 0 / 26%);backdrop-filter:blur(18px)}.section-input__panel>button{width:100%;display:grid;grid-template-columns:32px minmax(0,1fr) 17px;align-items:center;gap:9px;border:0;border-radius:9px;padding:7px 9px;color:var(--text-secondary);background:transparent;text-align:left}.section-input__panel>button:hover,.section-input__panel>button.active{color:var(--text-primary);background:var(--control-bg-hover)}.section-input__panel button>span:nth-child(2){min-width:0}.section-input__panel strong,.section-input__panel small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.section-input__panel strong{font-size:10px}.section-input__panel small{margin-top:2px;color:var(--text-muted);font-size:8px}.section-input__icon{width:29px;height:29px;display:grid;place-items:center;border-radius:9px;color:var(--accent);background:var(--accent-soft);font-size:14px}.section-input__create .section-input__icon{color:var(--success);background:color-mix(in srgb,var(--success) 10%,transparent);font-size:18px}.section-input__panel>p{margin:0;padding:12px;color:var(--text-muted);font-size:9px;text-align:center}.section-options-enter-active,.section-options-leave-active{transition:opacity .14s var(--ease-out),transform .14s var(--ease-out)}.section-options-enter-from,.section-options-leave-to{opacity:0;transform:translateY(-4px)}
</style>
